services:
  bikcraft-teste:
    image: bikcraft-teste
    container_name: bikcraft-teste
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - "8091:80"

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    privileged: true
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /usr/bin/docker:/usr/bin/docker