services:
  web-teste:
    image: bikcraft
    container_name: bikcraft-teste
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Estudos-bikcraft/css:/usr/share/nginx/html/css
    restart: always
    ports:
      - "8080:80"
